import { useState } from "react";
import { ArrowLeft, ArrowRight, CheckCircle2, Plus, Trash2 } from "lucide-react";
import type { Resume } from "@/domain/resume";
import { createId } from "@/domain/resume";

type Props = { resume: Resume; onChange: (next: Resume) => void; onImprove: (targetId: string) => void };

export function ProfileEditor({ resume, onChange }: Pick<Props, "resume" | "onChange">) {
  const [step, setStep] = useState(0);
  const updateContact = (key: keyof Resume["contact"], value: string) => onChange({ ...resume, contact: { ...resume.contact, [key]: value } });
  const steps = [
    { title: "Identitas", done: resume.contact.fullName.trim() && resume.targetRole.trim(), view: <div className="field-grid"><Field label="Nama lengkap" value={resume.contact.fullName} onChange={(value) => updateContact("fullName", value)} /><Field label="Target role" value={resume.targetRole} onChange={(value) => onChange({ ...resume, targetRole: value })} /></div> },
    { title: "Kontak", done: resume.contact.email.trim() && resume.contact.location.trim(), view: <div className="field-grid"><Field label="Email" type="email" value={resume.contact.email} onChange={(value) => updateContact("email", value)} /><Field label="Telepon" value={resume.contact.phone} onChange={(value) => updateContact("phone", value)} /><Field label="Kota / negara" value={resume.contact.location} onChange={(value) => updateContact("location", value)} /></div> },
    { title: "Link", done: resume.contact.linkedin.trim() || resume.contact.portfolio.trim(), view: <div className="field-grid"><Field label="LinkedIn" value={resume.contact.linkedin} onChange={(value) => updateContact("linkedin", value)} /><Field label="Portfolio / GitHub" value={resume.contact.portfolio} onChange={(value) => updateContact("portfolio", value)} /></div> },
  ];
  return <FocusFlow steps={steps} active={step} onStep={setStep} />;
}

export function ContentEditor({ resume, onChange, onImprove }: Props) {
  const [step, setStep] = useState(0);
  const steps = [
    { title: "Ringkasan", done: resume.summary.trim(), view: <div className="field-with-action"><TextArea label="Ringkasan profesional" value={resume.summary} rows={6} onChange={(value) => onChange({ ...resume, summary: value })} /><button type="button" className="text-button" onClick={() => onImprove("summary")}>Minta saran AI</button></div> },
    { title: "Keahlian", done: resume.skills.trim(), view: <div className="field-with-action"><TextArea label="Keahlian" helper="Pisahkan dengan koma; hanya masukkan keahlian yang benar-benar dimiliki." value={resume.skills} rows={4} onChange={(value) => onChange({ ...resume, skills: value })} /><button type="button" className="text-button" onClick={() => onImprove("skills")}>Minta saran AI</button></div> },
    { title: "Pengalaman", done: resume.experiences.some((item) => item.bullets.some((bullet) => bullet.text.trim())), view: <div className="editor-stack"><EntryHeader title="Pengalaman kerja" action="Tambah pengalaman" onAdd={() => onChange({ ...resume, experiences: [...resume.experiences, { id: createId(), role: "", company: "", location: "", startDate: "", endDate: "", bullets: [{ id: createId(), text: "" }] }] })} />
    {resume.experiences.map((item, index) => <div className="entry-card" key={item.id}>
      <div className="entry-card-head"><span>Pengalaman {index + 1}</span><IconButton label="Hapus pengalaman" onClick={() => onChange({ ...resume, experiences: resume.experiences.filter((entry) => entry.id !== item.id) })} /></div>
      <div className="field-grid"><Field label="Jabatan" value={item.role} onChange={(value) => updateExperience(resume, onChange, item.id, { role: value })} /><Field label="Perusahaan" value={item.company} onChange={(value) => updateExperience(resume, onChange, item.id, { company: value })} /><Field label="Lokasi" value={item.location} onChange={(value) => updateExperience(resume, onChange, item.id, { location: value })} /><div className="date-grid"><Field label="Mulai" value={item.startDate} placeholder="Jan 2024" onChange={(value) => updateExperience(resume, onChange, item.id, { startDate: value })} /><Field label="Selesai" value={item.endDate} placeholder="Sekarang" onChange={(value) => updateExperience(resume, onChange, item.id, { endDate: value })} /></div></div>
      <div className="bullet-list">{item.bullets.map((bullet, bulletIndex) => <div className="bullet-editor" key={bullet.id}><TextArea label={`Bullet ${bulletIndex + 1}`} value={bullet.text} rows={3} onChange={(value) => updateExperience(resume, onChange, item.id, { bullets: item.bullets.map((entry) => entry.id === bullet.id ? { ...entry, text: value } : entry) })} /><button type="button" className="text-button" onClick={() => onImprove(bullet.id)}>Perbaiki dengan AI</button><IconButton label="Hapus bullet" onClick={() => updateExperience(resume, onChange, item.id, { bullets: item.bullets.filter((entry) => entry.id !== bullet.id) })} /></div>)}</div>
      <button type="button" className="secondary-button compact" onClick={() => updateExperience(resume, onChange, item.id, { bullets: [...item.bullets, { id: createId(), text: "" }] })}><Plus size={16} /> Tambah bullet</button>
    </div>)}</div> },
    { title: "Pendidikan", done: resume.education.some((item) => item.degree.trim() || item.institution.trim()), view: <div className="editor-stack"><EntryHeader title="Pendidikan" action="Tambah pendidikan" onAdd={() => onChange({ ...resume, education: [...resume.education, { id: createId(), degree: "", institution: "", location: "", graduationDate: "" }] })} />
    {resume.education.map((item, index) => <div className="entry-card" key={item.id}><div className="entry-card-head"><span>Pendidikan {index + 1}</span><IconButton label="Hapus pendidikan" onClick={() => onChange({ ...resume, education: resume.education.filter((entry) => entry.id !== item.id) })} /></div><div className="field-grid"><Field label="Gelar / jurusan" value={item.degree} onChange={(value) => onChange({ ...resume, education: resume.education.map((entry) => entry.id === item.id ? { ...entry, degree: value } : entry) })} /><Field label="Institusi" value={item.institution} onChange={(value) => onChange({ ...resume, education: resume.education.map((entry) => entry.id === item.id ? { ...entry, institution: value } : entry) })} /><Field label="Lokasi" value={item.location} onChange={(value) => onChange({ ...resume, education: resume.education.map((entry) => entry.id === item.id ? { ...entry, location: value } : entry) })} /><Field label="Lulus" value={item.graduationDate} onChange={(value) => onChange({ ...resume, education: resume.education.map((entry) => entry.id === item.id ? { ...entry, graduationDate: value } : entry) })} /></div></div>)}
    </div> },
    { title: "Proyek", done: resume.projects.some((item) => item.name.trim() || item.bullets.some((bullet) => bullet.text.trim())), view: <div className="editor-stack"><EntryHeader title="Proyek" action="Tambah proyek" onAdd={() => onChange({ ...resume, projects: [...resume.projects, { id: createId(), name: "", technologies: "", date: "", bullets: [{ id: createId(), text: "" }] }] })} />
    {resume.projects.map((item, index) => <div className="entry-card" key={item.id}><div className="entry-card-head"><span>Proyek {index + 1}</span><IconButton label="Hapus proyek" onClick={() => onChange({ ...resume, projects: resume.projects.filter((entry) => entry.id !== item.id) })} /></div><div className="field-grid"><Field label="Nama proyek" value={item.name} onChange={(value) => updateProject(resume, onChange, item.id, { name: value })} /><Field label="Teknologi" value={item.technologies} onChange={(value) => updateProject(resume, onChange, item.id, { technologies: value })} /><Field label="Tanggal proyek" value={item.date} onChange={(value) => updateProject(resume, onChange, item.id, { date: value })} /></div><div className="bullet-list">{item.bullets.map((bullet, bulletIndex) => <div className="bullet-editor" key={bullet.id}><TextArea label={`Bullet proyek ${bulletIndex + 1}`} value={bullet.text} rows={3} onChange={(value) => updateProject(resume, onChange, item.id, { bullets: item.bullets.map((entry) => entry.id === bullet.id ? { ...entry, text: value } : entry) })} /><button type="button" className="text-button" onClick={() => onImprove(bullet.id)}>Perbaiki dengan AI</button><IconButton label="Hapus bullet proyek" onClick={() => updateProject(resume, onChange, item.id, { bullets: item.bullets.filter((entry) => entry.id !== bullet.id) })} /></div>)}</div><button type="button" className="secondary-button compact" onClick={() => updateProject(resume, onChange, item.id, { bullets: [...item.bullets, { id: createId(), text: "" }] })}><Plus size={16} /> Tambah bullet</button></div>)}
    </div> },
    { title: "Sertifikasi", done: resume.certifications.trim(), view: <TextArea label="Sertifikasi" value={resume.certifications} rows={5} onChange={(value) => onChange({ ...resume, certifications: value })} /> },
  ];
  return <FocusFlow steps={steps} active={step} onStep={setStep} />;
}

function updateExperience(resume: Resume, onChange: Props["onChange"], id: string, patch: Partial<Resume["experiences"][number]>) { onChange({ ...resume, experiences: resume.experiences.map((item) => item.id === id ? { ...item, ...patch } : item) }); }
function updateProject(resume: Resume, onChange: Props["onChange"], id: string, patch: Partial<Resume["projects"][number]>) { onChange({ ...resume, projects: resume.projects.map((item) => item.id === id ? { ...item, ...patch } : item) }); }
function EntryHeader({ title, action, onAdd }: { title: string; action: string; onAdd: () => void }) { return <div className="section-row"><h3>{title}</h3><button type="button" className="secondary-button compact" onClick={onAdd}><Plus size={16} />{action}</button></div>; }
function IconButton({ label, onClick }: { label: string; onClick: () => void }) { return <button type="button" className="icon-button danger" aria-label={label} title={label} onClick={onClick}><Trash2 size={17} /></button>; }
function FocusFlow({ steps, active, onStep }: { steps: Array<{ title: string; done: unknown; view: React.ReactNode }>; active: number; onStep: (next: number) => void }) {
  return <div className="focus-flow">
    <div className="focus-tabs" aria-label="Bagian formulir">{steps.map((item, index) => <button key={item.title} type="button" className={index === active ? "active" : ""} onClick={() => onStep(index)}><span>{item.done ? <CheckCircle2 size={14} /> : index + 1}</span>{item.title}</button>)}</div>
    <div className="focus-card" key={active}>{steps[active].view}</div>
    <div className="focus-actions">
      <button type="button" className="secondary-button" disabled={active === 0} onClick={() => onStep(Math.max(0, active - 1))}><ArrowLeft size={16} />Kembali</button>
      <button type="button" className="primary-button" disabled={active === steps.length - 1} onClick={() => onStep(Math.min(steps.length - 1, active + 1))}>Lanjut<ArrowRight size={16} /></button>
    </div>
  </div>;
}
export function Field({ label, value, onChange, type = "text", placeholder }: { label: string; value: string; onChange: (value: string) => void; type?: string; placeholder?: string }) { const id = `field-${label.toLowerCase().replace(/\W/g, "-")}`; return <label className="field" htmlFor={id}><span>{label}</span><input id={id} type={type} value={value} placeholder={placeholder} onChange={(event) => onChange(event.target.value)} /></label>; }
export function TextArea({ label, value, onChange, rows, helper }: { label: string; value: string; onChange: (value: string) => void; rows: number; helper?: string }) { const id = `field-${label.toLowerCase().replace(/\W/g, "-")}`; return <label className="field" htmlFor={id}><span>{label}</span>{helper ? <small>{helper}</small> : null}<textarea id={id} value={value} rows={rows} onChange={(event) => onChange(event.target.value)} /></label>; }
